# Generated by Django 3.1.7 on 2021-03-30 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField(default=0)),
                ('name', models.CharField(max_length=30)),
            ],
        ),
    ]
