"""
Django settings for azuresite project.

Generated by 'django-admin startproject' using Django 3.1.7.

For more information on this file, see
https://docs.djangoproject.com/en/3.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.1/ref/settings/
"""

import os
from pathlib import Path

# from azure.keyvault.secrets import SecretClient
# from azure.identity import DefaultAzureCredential


# # Start Key Vault
# key_vault_name = os.environ["Django__KeyVaultName"]
# key_vault_uri = f"https://{key_vault_name}.vault.azure.net"

# # See here for more information https://docs.microsoft.com/en-us/python/api/overview/azure/identity-readme?view=azure-python#defaultazurecredential
# credential = DefaultAzureCredential()
# key_vault_client = SecretClient(vault_url=key_vault_uri, credential=credential)

# # These string values should match the name of your secrets in the Key Vault
# postgresql_username = key_vault_client.get_secret('POSTGRESQL-Username').value
# postgresql_password = key_vault_client.get_secret('POSTGRESQL-Password').value
# postgresql_host_name = key_vault_client.get_secret('POSTGRESQL-HostName').value
# postgresql_database_name = key_vault_client.get_secret('POSTGRESQL-DatabaseName').value
# # End Key Vault


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'o^e+o_@ol4+nb_n79rz1_@^wbv4n4=801u@@c*-g*lhofl))%e'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []

LOGOUT_REDIRECT_URL = 'Index'


# Application definition

INSTALLED_APPS = [
    'adoptionsite.apps.AdoptionsiteConfig',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'azuresite.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'azuresite.wsgi.application'


AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend'
]


# Database
# https://docs.djangoproject.com/en/3.1/ref/settings/#databases

# Use local SQLite database
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# # Start PostgreSQL
# # Uncomment this and read in the details from your Key Vault variables to connect to PostgreSQL
# # MAKE SURE THAT YOUR REMOVE THE SQL LITE DEFINITION ABOVE ONCE YOU ADD POSTGRESQL SUPPORT
# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.postgresql',
#         'NAME': f'{postgresql_database_name}',
#         'USER': f'{postgresql_username}@{postgresql_host_name}',
#         'PASSWORD': f'{postgresql_password}',
#         'HOST': f'{postgresql_host_name}.postgres.database.azure.com',
#         'PORT': '5432',
#         'OPTIONS': {
#             'sslmode': 'require'
#         },
#     }
# }
# # End PostgreSQL


# Password validation
# https://docs.djangoproject.com/en/3.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.1/topics/i18n/

LANGUAGE_CODE = 'en-NZ'

TIME_ZONE = 'Pacific/Auckland'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.1/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
